name: zero
description: "Android and IOS App written in Flutter to browse images from many hentai API's."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bloc: ^6.0.0
  cached_network_image: ^2.2.0+1
  flutter_bloc: ^6.0.0
  cupertino_icons: ^0.1.3
  dio: ^3.0.10
  string_validator: ^0.1.4
  shared_preferences: ^0.5.8
  diacritic: ^0.1.1
  url_launcher: ^5.5.0
  mobx: ^1.2.1+1
  flutter_mobx: ^1.1.0+1
  get_it: ^4.0.4
  firebase_database: ^3.1.6
  path_provider: ^1.6.11
  flutter:
    sdk: flutter

dev_dependencies:
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.1
  mockito: ^4.1.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner

scripts:
  coverage: flutter test --coverage & remove_from_coverage -f coverage/lcov.info -r .g.dart$
  mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
