name: "ui_palette_example"
environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  equatable: ^1.2.6
  cupertino_icons: ^1.0.0

  # Flutter deps
  flutter:
    sdk: flutter

  # Local deps
  app_utils:
    git: https://github.com/AnimeDart/dart-utils

  # Local deps
  ui_palette:
    path: ..

dev_dependencies:
  effective_dart: ^1.0.0
  test: ^1.15.7

flutter:
  uses-material-design: true

  fonts:
    - family: Josefin Sans
      fonts:
        - asset: assets/fonts/JosefinSans-Bold.ttf
        - asset: assets/fonts/JosefinSans-Italic.ttf
        - asset: assets/fonts/JosefinSans-Regular.ttf
          weight: 700
